apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  name: jekyll-site
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: jekyll-site
